### ISSUE TITLE
getHistoricalCountByArea test fails in newer node versions

### ISSUE THREAD

**Issue by matthewberryman** [smart-facility/cognicity-server#20] opened 2015-10-14 04:43 UTC
## Description
This is with node v4.1.2 (latest available with [homebrew](http://brew.sh) `brew update && brew install node`) but I suspect also common to newer io.js-derived node.js versions across platforms that care about properties being read only. I suspect [strict mode](https://msdn.microsoft.com/en-us/library/br230269%28v=vs.94%29.aspx?f=255&MSPPError=-2147217396) is enable now by default and that is throwing the error because of the way those variables are defined.

## Output of npm test 
52 passing (883ms)
 1 failing

 1) getHistoricalCountByArea validation should call the database if parameters are valid:
     TypeError: Cannot assign to read only property 'start_time' of ale
      at chainQueries ([CognicityServer.js:433](https://github.com/smart-facility/cognicity-server/blob/master/CognicityServer.js#L433):21)
      at Object.server.getCountByArea ([test/testCognicityServer.js:631](https://github.com/smart-facility/cognicity-server/blob/master/test/testCognicityServer.js#L631):4)
      at Object.CognicityServer.getHistoricalCountByArea ([CognicityServer.js:452](https://github.com/smart-facility/cognicity-server/blob/master/CognicityServer.js#L452):8)
      at Context.<anonymous> ([test/testCognicityServer.js:642](https://github.com/smart-facility/cognicity-server/blob/master/test/testCognicityServer.js#L642):10)

**Comment by matthewberryman** [comment] 2015-10-15 00:37
I also had this happen on node v0.10.26 on jenkins as well.

**Comment by talltom** [comment] 2015-10-15 06:27
This passes on node v0.10.40 on [Travis](https://travis-ci.org/smart-facility/cognicity-server/builds/85440003). An environmental variable tripping us up?

**Comment by matthewberryman** [comment] 2015-10-15 06:30
Sorry, typo: I meant 0.12.6
No relevant environment variables set on the two boxes I've seen this on.

**Comment by talltom** [comment] 2015-10-15 06:35
Confirmed failes on node v0.12.7 in [Travis](https://travis-ci.org/smart-facility/cognicity-server/builds/85473296)

**Comment by matthewberryman** [comment] 2015-11-20 04:04
@benatwork99 please fix in master and 2.0.x

**Comment by benatwork99** [comment] 2015-11-20 06:07
WIll do. Looking at the code what was there seems wrong, a slight change will make it more correct. I'll also update node to v12 for cognicity-rem-server, do we want to update node to v12 for cognicity-server?

**Comment by matthewberryman** [comment] 2015-11-20 06:08
I've already bumped it up (at least in 2.0.x) for cognicity-server and cognicity-rem-server to 4.2.1 which is what we use for dev and prod.

**Comment by benatwork99** [comment] 2015-11-20 06:10
Ok great. I'll update the version Travis uses when I commit so we can see the test pass.

**Comment by matthewberryman** [comment] 2015-11-20 06:11
I've already done that too, and it still fails. https://travis-ci.org/smart-facility/cognicity-server/builds/92194867

**Comment by matthewberryman** [comment] 2015-11-20 06:11
See https://github.com/smart-facility/cognicity-server/commit/9feeca81a7106470656559187e9aa115740f8e4b

**Comment by benatwork99** [comment] 2015-11-23 00:17
I am about to push a fix for this, I notice a build error in the Travis build (expand the 'npm install' section) https://travis-ci.org/smart-facility/cognicity-server/builds/92194867

```
> pg@3.6.3 install /home/travis/build/smart-facility/cognicity-server/node_modules/pg
> node-gyp rebuild || (exit 0)
make: Entering directory `/home/travis/build/smart-facility/cognicity-server/node_modules/pg/build'
  CXX(target) Release/obj.target/binding/src/binding.o
In file included from /home/travis/.node-gyp/4.2.1/include/node/node.h:42:0,
                 from ../node_modules/nan/nan.h:23,
                 from ../src/binding.cc:3:
/home/travis/.node-gyp/4.2.1/include/node/v8.h:336:1: error: expected unqualified-id before ‘using’
/home/travis/.node-gyp/4.2.1/include/node/v8.h:469:1: error: expected unqualified-id before ‘using’
/home/travis/.node-gyp/4.2.1/include/node/v8.h:852:1: error: expected unqualified-id before ‘using’
In file included from ../src/binding.cc:3:0:
../node_modules/nan/nan.h:74:9: error: ‘v8::Handle’ has not been declared
../node_modules/nan/nan.h:74:15: error: expected ‘,’ or ‘...’ before ‘<’ token
...
```

I see the same build error locally using node 4.x or 5.x. 

I will look into what this means, it looks like a fatal build error but the build then continues.

**Comment by matthewberryman** [comment] 2015-11-23 00:24
That version of pg depends on a version of nan that has issues with newer nodejs (a common issue - see https://github.com/nodejs/node/issues/2798 ). Safe to disregard that, as well as warnings from lack of postgres libraries—pg will work without native libraries; we do install the native libraries on our dev and prod boxes, see https://github.com/smart-facility/cognicity-server/blob/master/.ebextensions/packages.config for example on AWS EB.

**Comment by matthewberryman** [comment] 2015-11-23 01:14
Closed by 6d331b8

**Comment by benatwork99** [comment] 2015-11-23 01:19
FYI I have not fixed on master yet am about to do that now.

**Comment by matthewberryman** [comment] 2015-11-23 01:20
Sorry, caught the 2.0.x commit but forgot about master. Use closes keyword in commit message.

**Closed** 2015-11-23 01:24 UTC
